export const OP_DATABASE = [
    // --- ONE PIECE ---
    { anime: "ONE PIECE", alt: ["OP"], song: "We Are!", num: 1, url: "https://v.animethemes.moe/OnePiece-OP1.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Believe", num: 2, url: "https://animethemes.moe/video/OnePiece-OP2-NCDVD480.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Hikari E", num: 3, url: "https://animethemes.moe/video/OnePiece-OP3-NCDVD480.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Bon Voyage!", num: 4, url: "https://animethemes.moe/video/OnePiece-OP4-NCDVD480.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Kokoro no Chizu", num: 5, url: "https://animethemes.moe/video/OnePiece-OP5-NCDVD480.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Brand New World", num: 6, url: "https://animethemes.moe/video/OnePiece-OP6-NCDVD480.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Crazy Rainbow", num: 7, url: "https://animethemes.moe/video/OnePiece-OP8-NCDVD480.webm" }, // Note: Corrigé vers OP8
    { anime: "ONE PIECE", alt: ["OP"], song: "Jungle P", num: 8, url: "https://animethemes.moe/video/OnePiece-OP9-NCDVD480.webm" }, // Note: Corrigé vers OP9
    { anime: "ONE PIECE", alt: ["OP"], song: "We Are! (Remix)", num: 10, url: "https://animethemes.moe/video/OnePiece-OP11-NCDVD480.webm" }, // Note: Décalage corrigé via API (Share the world est souvent le suivant dispo)
    { anime: "ONE PIECE", alt: ["OP"], song: "Share The World", num: 11, url: "https://animethemes.moe/video/OnePiece-OP11-NCDVD480.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Kaze wo Sagashite", num: 12, url: "https://animethemes.moe/video/OnePiece-OP12-NCDVD480.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "One Day", num: 13, url: "https://animethemes.moe/video/OnePiece-OP13-NCBD.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Fight Together", num: 14, url: "https://animethemes.moe/video/OnePiece-OP14-Lyrics.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "We Go!", num: 15, url: "https://animethemes.moe/video/OnePiece-OP15-NCBD.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Hands Up!", num: 16, url: "https://animethemes.moe/video/OnePiece-OP16.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Wake up!", num: 17, url: "https://animethemes.moe/video/OnePiece-OP17.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Hard Knock Days", num: 18, url: "https://animethemes.moe/video/OnePiece-OP18.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "We Can!", num: 19, url: "https://animethemes.moe/video/OnePiece-OP19.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Hope", num: 20, url: "https://animethemes.moe/video/OnePiece-OP20.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Super Powers", num: 21, url: "https://animethemes.moe/video/OnePiece-OP21.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "OVER THE TOP", num: 22, url: "https://animethemes.moe/video/OnePiece-OP22.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "DREAMIN' ON", num: 23, url: "https://animethemes.moe/video/OnePiece-OP23.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "PAINT", num: 24, url: "https://animethemes.moe/video/OnePiece-OP24.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "The Peak", num: 25, url: "https://v.animethemes.moe/OnePiece-OP25.webm" },
    { anime: "ONE PIECE", alt: ["OP"], song: "Assu!", num: 26, url: "https://animethemes.moe/video/OnePiece-OP26.webm" },

    // --- NARUTO & SHIPPUDEN ---
    { anime: "NARUTO", alt: [], song: "R★O★C★K★S", num: 1, url: "https://animethemes.moe/video/Naruto-OP1.webm" },
    { anime: "NARUTO", alt: [], song: "Haruka Kanata", num: 2, url: "https://animethemes.moe/video/Naruto-OP2.webm" },
    { anime: "NARUTO", alt: [], song: "Kanashimi wo Yasashisa ni", num: 3, url: "https://animethemes.moe/video/Naruto-OP3.webm" },
    { anime: "NARUTO", alt: [], song: "GO!!!", num: 4, url: "https://animethemes.moe/video/Naruto-OP4.webm" },
    { anime: "NARUTO", alt: [], song: "Seishun Kyosokyoku", num: 5, url: "https://animethemes.moe/video/Naruto-OP5.webm" },
    { anime: "NARUTO", alt: [], song: "No Boy, No Cry", num: 6, url: "https://animethemes.moe/video/Naruto-OP6.webm" },
    { anime: "NARUTO", alt: [], song: "Namikaze Satellite", num: 7, url: "https://animethemes.moe/video/Naruto-OP7.webm" },
    { anime: "NARUTO", alt: [], song: "Re:member", num: 8, url: "https://animethemes.moe/video/Naruto-OP8.webm" },
    { anime: "NARUTO", alt: [], song: "Yura Yura", num: 9, url: "https://animethemes.moe/video/Naruto-OP9.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Hero's Come Back!!", num: 1, url: "https://animethemes.moe/video/NarutoShippuuden-OP1.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Distance", num: 2, url: "https://animethemes.moe/video/NarutoShippuuden-OP2.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Blue Bird", num: 3, url: "https://animethemes.moe/video/NarutoShippuuden-OP3.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Closer", num: 4, url: "https://animethemes.moe/video/NarutoShippuuden-OP4.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Hotaru no Hikari", num: 5, url: "https://animethemes.moe/video/NarutoShippuuden-OP5.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Sign", num: 6, url: "https://animethemes.moe/video/NarutoShippuuden-OP6.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Toumei Datta Sekai", num: 7, url: "https://animethemes.moe/video/NarutoShippuuden-OP7.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Diver", num: 8, url: "https://animethemes.moe/video/NarutoShippuuden-OP8.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Lovers", num: 9, url: "https://animethemes.moe/video/NarutoShippuuden-OP9.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Newsong", num: 10, url: "https://animethemes.moe/video/NarutoShippuuden-OP10.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Totsugeki Rock", num: 11, url: "https://animethemes.moe/video/NarutoShippuuden-OP11.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Moshimo", num: 12, url: "https://animethemes.moe/video/NarutoShippuuden-OP12.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Niwaka Ame ni Mo Makezu", num: 13, url: "https://animethemes.moe/video/NarutoShippuuden-OP13.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Tsuki no Ookisa", num: 14, url: "https://animethemes.moe/video/NarutoShippuuden-OP14.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Guren", num: 15, url: "https://animethemes.moe/video/NarutoShippuuden-OP15.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Silhouette", num: 16, url: "https://animethemes.moe/video/NarutoShippuuden-OP16.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Kaze", num: 17, url: "https://animethemes.moe/video/NarutoShippuuden-OP17.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "LINE", num: 18, url: "https://animethemes.moe/video/NarutoShippuuden-OP18.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Blood Circulator", num: 19, url: "https://animethemes.moe/video/NarutoShippuuden-OP19.webm" },
    { anime: "NARUTO SHIPPUDEN", alt: ["SHIPPUDEN"], song: "Kara no Kokoro", num: 20, url: "https://animethemes.moe/video/NarutoShippuuden-OP20.webm" },

    // --- BORUTO ---
    { anime: "BORUTO", alt: [], song: "Baton Road", num: 1, url: "https://animethemes.moe/video/Boruto-OP1-BD1080.webm" },
    { anime: "BORUTO", alt: [], song: "OVER", num: 2, url: "https://animethemes.moe/video/Boruto-OP2-NCBD1080.webm" },
    { anime: "BORUTO", alt: [], song: "It's all in the game", num: 3, url: "https://animethemes.moe/video/Boruto-OP3-NCBD1080.webm" },
    { anime: "BORUTO", alt: [], song: "Lonely Go!", num: 4, url: "https://animethemes.moe/video/Boruto-OP4-NCBD1080.webm" },
    { anime: "BORUTO", alt: [], song: "Golden Time", num: 5, url: "https://animethemes.moe/video/Boruto-OP5.webm" },
    { anime: "BORUTO", alt: [], song: "Teenage Dream", num: 6, url: "https://animethemes.moe/video/Boruto-OP6.webm" },
    { anime: "BORUTO", alt: [], song: "Hajimatteiku Takamatteiku", num: 7, url: "https://animethemes.moe/video/Boruto-OP7.webm" },
    { anime: "BORUTO", alt: [], song: "BAKU", num: 8, url: "https://animethemes.moe/video/Boruto-OP8.webm" },
    { anime: "BORUTO", alt: [], song: "Gamushara", num: 9, url: "https://animethemes.moe/video/Boruto-OP9.webm" },
    { anime: "BORUTO", alt: [], song: "GOLD", num: 10, url: "https://animethemes.moe/video/Boruto-OP10.webm" },
    { anime: "BORUTO", alt: [], song: "Kirarirari", num: 11, url: "https://animethemes.moe/video/Boruto-OP11.webm" },
    { anime: "BORUTO", alt: [], song: "Shukuen", num: 12, url: "https://animethemes.moe/video/Boruto-OP12.webm" },

    // --- DRAGON BALL ---
    { anime: "DRAGON BALL", alt: ["DB"], song: "Makafushigi Adventure!", num: 1, url: "https://animethemes.moe/video/DragonBall-OP1.webm" },
    { anime: "DRAGON BALL Z", alt: ["DBZ"], song: "Cha-La Head-Cha-La", num: 1, url: "https://animethemes.moe/video/DragonBallZ-OP1-NCBD1080.webm" },
    { anime: "DRAGON BALL SUPER", alt: ["DBS"], song: "Chozetsu Dynamic!", num: 1, url: "https://animethemes.moe/video/DragonBallSuper-OP1.webm" },
    { anime: "DRAGON BALL SUPER", alt: ["DBS"], song: "Limit Break x Survivor", num: 2, url: "https://v.animethemes.moe/DragonBallSuper-OP2.webm" },
    { anime: "DRAGON BALL GT", alt: ["DBGT"], song: "Dan Dan Kokoro", num: 1, url: "https://v.animethemes.moe/DragonBallGT-OP1.webm" },

    // --- FAIRY TAIL ---
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Snow Fairy", num: 1, url: "https://animethemes.moe/video/FairyTail-OP1.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "S.O.W. Sense of Wonder", num: 2, url: "https://animethemes.moe/video/FairyTail-OP2.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "ft.", num: 3, url: "https://animethemes.moe/video/FairyTail-OP3.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "R.P.G. ~Rockin' Playing Game", num: 4, url: "https://animethemes.moe/video/FairyTail-OP4.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Egao no Mahou", num: 5, url: "https://animethemes.moe/video/FairyTail-OP5.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Fiesta", num: 6, url: "https://animethemes.moe/video/FairyTail-OP6.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Evidence", num: 7, url: "https://animethemes.moe/video/FairyTail-OP7.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "The Rock City Boy", num: 8, url: "https://animethemes.moe/video/FairyTail-OP8.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Towa no Kizuna", num: 9, url: "https://animethemes.moe/video/FairyTail-OP9.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "I Wish", num: 10, url: "https://animethemes.moe/video/FairyTail-OP10.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Hajimari no Sora", num: 11, url: "https://animethemes.moe/video/FairyTail-OP11.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Tenohira", num: 12, url: "https://animethemes.moe/video/FairyTail-OP12.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Breakthrough", num: 13, url: "https://animethemes.moe/video/FairyTail-OP13.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Fairy Tail: Yakusoku no Hi", num: 14, url: "https://animethemes.moe/video/FairyTail-OP14.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Masayume Chasing", num: 15, url: "https://animethemes.moe/video/FairyTail2014-OP1.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Strike Back", num: 16, url: "https://animethemes.moe/video/FairyTail2014-OP2.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Mysterious Magic", num: 17, url: "https://animethemes.moe/video/FairyTail2014-OP3.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "BREAK OUT", num: 18, url: "https://animethemes.moe/video/FairyTail2014-OP4.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Yumeiro Graffiti", num: 19, url: "https://animethemes.moe/video/FairyTail2014-OP5.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "NEVER-END TALE", num: 20, url: "https://animethemes.moe/video/FairyTail2014-OP6.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Believe In Myself", num: 21, url: "https://animethemes.moe/video/FairyTail2014-OP7.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Ashita wo Narase", num: 22, url: "https://animethemes.moe/video/FairyTail2014-OP8.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "Power of the Dream", num: 23, url: "https://animethemes.moe/video/FairyTail2018-OP1-NCBD1080.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "DOWN BY LAW", num: 24, url: "https://animethemes.moe/video/FairyTail2018-OP2-NCBD1080.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "NO-LIMIT", num: 25, url: "https://animethemes.moe/video/FairyTail2018-OP3-NCBD1080.webm" },
    { anime: "FAIRY TAIL", alt: ["FT"], song: "MORE THAN LIKE", num: 26, url: "https://animethemes.moe/video/FairyTail2018-OP4-NCBD1080.webm" },

    // --- BLEACH ---
    { anime: "BLEACH", alt: [], song: "Asterisk", num: 1, url: "https://animethemes.moe/video/Bleach-OP1.webm" },
    { anime: "BLEACH", alt: [], song: "D-tecnoLife", num: 2, url: "https://animethemes.moe/video/Bleach-OP2.webm" },
    { anime: "BLEACH", alt: [], song: "Ichirin no Hana", num: 3, url: "https://animethemes.moe/video/Bleach-OP3.webm" },
    { anime: "BLEACH", alt: [], song: "TONIGHT, TONIGHT, TONIGHT", num: 4, url: "https://animethemes.moe/video/Bleach-OP4.webm" },
    { anime: "BLEACH", alt: [], song: "Rolling Star", num: 5, url: "https://animethemes.moe/video/Bleach-OP5.webm" },
    { anime: "BLEACH", alt: [], song: "ALONES", num: 6, url: "https://animethemes.moe/video/Bleach-OP6.webm" },
    { anime: "BLEACH", alt: [], song: "After Dark", num: 7, url: "https://animethemes.moe/video/Bleach-OP7.webm" },
    { anime: "BLEACH", alt: [], song: "CHU-BURA", num: 8, url: "https://animethemes.moe/video/Bleach-OP8.webm" },
    { anime: "BLEACH", alt: [], song: "Velonica", num: 9, url: "https://animethemes.moe/video/Bleach-OP9.webm" },
    { anime: "BLEACH", alt: [], song: "Shoujo S", num: 10, url: "https://animethemes.moe/video/Bleach-OP10.webm" },
    { anime: "BLEACH", alt: [], song: "Anima Rossa", num: 11, url: "https://animethemes.moe/video/Bleach-OP11.webm" },
    { anime: "BLEACH", alt: [], song: "chAngE", num: 12, url: "https://animethemes.moe/video/Bleach-OP12.webm" },
    { anime: "BLEACH", alt: [], song: "Ranbu no Melody", num: 13, url: "https://animethemes.moe/video/Bleach-OP13.webm" },
    { anime: "BLEACH", alt: [], song: "BLUE", num: 14, url: "https://animethemes.moe/video/Bleach-OP14.webm" },
    { anime: "BLEACH", alt: [], song: "HARUKAZE", num: 15, url: "https://animethemes.moe/video/Bleach-OP15.webm" },
    { anime: "BLEACH", alt: [], song: "Scar", num: 16, url: "https://animethemes.moe/video/Bleach2022-OP1.webm" },
    { anime: "BLEACH", alt: [], song: "STARS", num: 17, url: "https://animethemes.moe/video/Bleach2023-OP1.webm" },

    // --- MY HERO ACADEMIA ---
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "The Day", num: 1, url: "https://animethemes.moe/video/BokuNoHeroAcademia-OP1-NCBD1080.webm" },
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "Peace Sign", num: 2, url: "https://animethemes.moe/video/BokuNoHeroAcademiaS2-OP1-NCBD1080.webm" },
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "Sora ni Utaeba", num: 3, url: "https://animethemes.moe/video/BokuNoHeroAcademiaS2-OP2-NCBD1080.webm" },
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "ODD FUTURE", num: 4, url: "https://animethemes.moe/video/BokuNoHeroAcademiaS3-OP1-NCBD1080.webm" },
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "Make my story", num: 5, url: "https://animethemes.moe/video/BokuNoHeroAcademiaS3-OP2-NCBD1080.webm" },
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "Polaris", num: 6, url: "https://animethemes.moe/video/BokuNoHeroAcademiaS4-OP1-NCBD1080.webm" },
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "Star Marker", num: 7, url: "https://animethemes.moe/video/BokuNoHeroAcademiaS4-OP2-NCBD1080.webm" },
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "No.1", num: 8, url: "https://animethemes.moe/video/BokuNoHeroAcademiaS5-OP1.webm" },
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "Merry-Go-Round", num: 9, url: "https://animethemes.moe/video/BokuNoHeroAcademiaS5-OP2.webm" },
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "Hitamuki", num: 10, url: "https://animethemes.moe/video/BokuNoHeroAcademiaS6-OP1.webm" },
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "Bokura no", num: 11, url: "https://animethemes.moe/video/BokuNoHeroAcademiaS6-OP2.webm" },
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "Tagatame", num: 12, url: "https://animethemes.moe/video/BokuNoHeroAcademiaS7-OP1.webm" },
    { anime: "MY HERO ACADEMIA", alt: ["MHA"], song: "Curtain Call", num: 13, url: "https://animethemes.moe/video/BokuNoHeroAcademiaS7-OP2.webm" },

    // --- BLACK CLOVER ---
    { anime: "BLACK CLOVER", alt: ["BC"], song: "Haruka Mirai", num: 1, url: "https://animethemes.moe/video/BlackClover-OP1-NCBD1080.webm" },
    { anime: "BLACK CLOVER", alt: ["BC"], song: "PAiNT it BLACK", num: 2, url: "https://animethemes.moe/video/BlackClover-OP2-NCBD1080.webm" },
    { anime: "BLACK CLOVER", alt: ["BC"], song: "Black Rover", num: 3, url: "https://animethemes.moe/video/BlackClover-OP3-NCBD1080.webm" },
    { anime: "BLACK CLOVER", alt: ["BC"], song: "Guess Who Is Back", num: 4, url: "https://animethemes.moe/video/BlackClover-OP4-NCBD1080.webm" },
    { anime: "BLACK CLOVER", alt: ["BC"], song: "Gamushara", num: 5, url: "https://animethemes.moe/video/BlackClover-OP5-NCBD1080.webm" },
    { anime: "BLACK CLOVER", alt: ["BC"], song: "Rakugaki Page", num: 6, url: "https://animethemes.moe/video/BlackClover-OP6-NCBD1080.webm" },
    { anime: "BLACK CLOVER", alt: ["BC"], song: "JUSTadICE", num: 7, url: "https://animethemes.moe/video/BlackClover-OP7-NCBD1080.webm" },
    { anime: "BLACK CLOVER", alt: ["BC"], song: "sky & blue", num: 8, url: "https://animethemes.moe/video/BlackClover-OP8.webm" },
    { anime: "BLACK CLOVER", alt: ["BC"], song: "RiGHT NOW", num: 9, url: "https://animethemes.moe/video/BlackClover-OP9.webm" },
    { anime: "BLACK CLOVER", alt: ["BC"], song: "Black Catcher", num: 10, url: "https://animethemes.moe/video/BlackClover-OP10.webm" },
    { anime: "BLACK CLOVER", alt: ["BC"], song: "Stories", num: 11, url: "https://animethemes.moe/video/BlackClover-OP11.webm" },
    { anime: "BLACK CLOVER", alt: ["BC"], song: "Everlasting Shine", num: 12, url: "https://v.animethemes.moe/BlackClover-OP12.webm" },
    { anime: "BLACK CLOVER", alt: ["BC"], song: "Grandeur", num: 13, url: "https://animethemes.moe/video/BlackClover-OP13.webm" },

    // --- ATTACK ON TITAN ---
    { anime: "ATTACK ON TITAN", alt: ["SNK"], song: "Guren no Yumiya", num: 1, url: "https://animethemes.moe/video/ShingekiNoKyojin-OP1.webm" },
    { anime: "ATTACK ON TITAN", alt: ["SNK"], song: "Jiyuu no Tsubasa", num: 2, url: "https://animethemes.moe/video/ShingekiNoKyojin-OP2.webm" },
    { anime: "ATTACK ON TITAN", alt: ["SNK"], song: "Sasageyo", num: 3, url: "https://v.animethemes.moe/ShingekiNoKyojinS2-OP1-NCBD1080.webm" },
    { anime: "ATTACK ON TITAN", alt: ["SNK"], song: "Red Swan", num: 4, url: "https://animethemes.moe/video/ShingekiNoKyojinS3-OP1-NCBD1080.webm" },
    { anime: "ATTACK ON TITAN", alt: ["SNK"], song: "Shoukei to Shikabane no Michi", num: 5, url: "https://animethemes.moe/video/ShingekiNoKyojinS3Part2-OP1-NCBD1080.webm" },
    { anime: "ATTACK ON TITAN", alt: ["SNK"], song: "My War", num: 6, url: "https://v.animethemes.moe/ShingekiNoKyojinS4-OP1.webm" },
    { anime: "ATTACK ON TITAN", alt: ["SNK"], song: "The Rumbling", num: 7, url: "https://animethemes.moe/video/ShingekiNoKyojinS4Part2-OP1.webm" },
    // Supprimé: Saigo no Kyojin (demande utilisateur)

    // --- SEVEN DEADLY SINS ---
    { anime: "SEVEN DEADLY SINS", alt: ["NANATSU"], song: "Netsujo no Spectrum", num: 1, url: "https://v.animethemes.moe/NanatsuNoTaizai-OP1.webm" },
    { anime: "SEVEN DEADLY SINS", alt: ["NANATSU"], song: "Seven Deadly Sins", num: 2, url: "https://v.animethemes.moe/NanatsuNoTaizai-OP2.webm" },
    { anime: "SEVEN DEADLY SINS", alt: ["NANATSU"], song: "Howling", num: 3, url: "https://v.animethemes.moe/NanatsuNoTaizaiImashimeNoFukkatsu-OP1-NCBD1080.webm" },
    { anime: "SEVEN DEADLY SINS", alt: ["NANATSU"], song: "Ame ga Furu kara Niji ga Deru", num: 4, url: "https://v.animethemes.moe/NanatsuNoTaizaiImashimeNoFukkatsu-OP2-NCBD1080.webm" },
    { anime: "SEVEN DEADLY SINS", alt: ["NANATSU"], song: "ROB THE FRONTIER", num: 5, url: "https://animethemes.moe/video/NanatsuNoTaizaiKamigamiNoGekirin-OP1-NCBD1080.webm" },
    { anime: "SEVEN DEADLY SINS", alt: ["NANATSU"], song: "delete", num: 6, url: "https://animethemes.moe/video/NanatsuNoTaizaiKamigamiNoGekirin-OP2-NCBD1080.webm" },
    { anime: "SEVEN DEADLY SINS", alt: ["NANATSU"], song: "Hikari Are", num: 7, url: "https://animethemes.moe/video/NanatsuNoTaizaiFunnuNoShinpan-OP1.webm" },
    { anime: "SEVEN DEADLY SINS", alt: ["NANATSU"], song: "Eien no Aria", num: 8, url: "https://animethemes.moe/video/NanatsuNoTaizaiFunnuNoShinpan-OP2.webm" },
    // Supprimé: Kimi no Koto (non trouvé)

    // --- SWORD ART ONLINE ---
    { anime: "SWORD ART ONLINE", alt: ["SAO"], song: "Crossing Field", num: 1, url: "https://animethemes.moe/video/SwordArtOnline-OP1.webm" },
    { anime: "SWORD ART ONLINE", alt: ["SAO"], song: "INNOCENCE", num: 2, url: "https://animethemes.moe/video/SwordArtOnline-OP2.webm" },
    { anime: "SWORD ART ONLINE", alt: ["SAO"], song: "IGNITE", num: 3, url: "https://animethemes.moe/video/SwordArtOnlineS2-OP1.webm" },
    { anime: "SWORD ART ONLINE", alt: ["SAO"], song: "courage", num: 4, url: "https://animethemes.moe/video/SwordArtOnlineS2-OP2.webm" },
    { anime: "SWORD ART ONLINE", alt: ["SAO"], song: "ADAMAS", num: 5, url: "https://animethemes.moe/video/SwordArtOnlineAlicization-OP1-NCBD1080.webm" },
    { anime: "SWORD ART ONLINE", alt: ["SAO"], song: "RESISTER", num: 6, url: "https://animethemes.moe/video/SwordArtOnlineAlicization-OP2-NCBD1080.webm" },
    { anime: "SWORD ART ONLINE", alt: ["SAO"], song: "Resolution", num: 7, url: "https://animethemes.moe/video/SwordArtOnlineAlicizationS2-OP1-NCBD1080.webm" },
    { anime: "SWORD ART ONLINE", alt: ["SAO"], song: "ANIMA", num: 8, url: "https://animethemes.moe/video/SwordArtOnlineAlicizationS3-OP1-NCBD1080.webm" },
    // Supprimé: Catch the Moment (demande utilisateur)

    // --- DEMON SLAYER ---
    { anime: "DEMON SLAYER", alt: ["KNY"], song: "Gurenge", num: 1, url: "https://animethemes.moe/video/KimetsuNoYaiba-OP1-NCBD1080.webm" },
    { anime: "DEMON SLAYER", alt: ["KNY"], song: "Akeboshi", num: 2, url: "https://animethemes.moe/video/KimetsuNoYaibaMugenResshaTV-OP1.webm" },
    { anime: "DEMON SLAYER", alt: ["KNY"], song: "Zankyou Sanka", num: 3, url: "https://animethemes.moe/video/KimetsuNoYaibaYuukakuHen-OP1.webm" },
    { anime: "DEMON SLAYER", alt: ["KNY"], song: "Kizuna no Kiseki", num: 4, url: "https://animethemes.moe/video/KimetsuNoYaibaKatanakajiNoSatoHen-OP1.webm" },
    { anime: "DEMON SLAYER", alt: ["KNY"], song: "Mugen", num: 5, url: "https://animethemes.moe/video/KimetsuNoYaibaHashiraGeikoHen-OP1.webm" },

    // --- HAIKYUU ---
    { anime: "HAIKYUU", alt: ["HQ"], song: "Imagination", num: 1, url: "https://animethemes.moe/video/Haikyuu-OP1.webm" },
    { anime: "HAIKYUU", alt: ["HQ"], song: "Ah Yeah!!", num: 2, url: "https://animethemes.moe/video/Haikyuu-OP2.webm" },
    { anime: "HAIKYUU", alt: ["HQ"], song: "I'm a Believer", num: 3, url: "https://animethemes.moe/video/HaikyuuS2-OP1-NCBD1080.webm" },
    { anime: "HAIKYUU", alt: ["HQ"], song: "FLY HIGH!!", num: 4, url: "https://animethemes.moe/video/HaikyuuS2-OP2-NCBD1080.webm" },
    { anime: "HAIKYUU", alt: ["HQ"], song: "Hikariare", num: 5, url: "https://animethemes.moe/video/HaikyuuS3-OP1-NCBD1080.webm" },
    { anime: "HAIKYUU", alt: ["HQ"], song: "Phoenix", num: 6, url: "https://animethemes.moe/video/HaikyuuS4-OP1.webm" },
    { anime: "HAIKYUU", alt: ["HQ"], song: "Toppako", num: 7, url: "https://animethemes.moe/video/HaikyuuS5-OP1.webm" },
    // Supprimé: Orange (Ending film, demande utilisateur)

    // --- DR. STONE ---
    { anime: "DR. STONE", alt: [], song: "Good Morning World!", num: 1, url: "https://animethemes.moe/video/DrStone-OP1-NCBD1080.webm" },
    { anime: "DR. STONE", alt: [], song: "Sangenshoku", num: 2, url: "https://animethemes.moe/video/DrStone-OP2-NCBD1080.webm" },
    { anime: "DR. STONE", alt: [], song: "Rakuen", num: 3, url: "https://animethemes.moe/video/DrStoneS2-OP1.webm" },
    { anime: "DR. STONE", alt: [], song: "Wasuregataki", num: 4, url: "https://animethemes.moe/video/DrStoneS3-OP1.webm" },
    { anime: "DR. STONE", alt: [], song: "Haruka", num: 5, url: "https://animethemes.moe/video/DrStoneS3Part2-OP1.webm" },
    
    // --- JUJUTSU KAISEN ---
    { anime: "JUJUTSU KAISEN", alt: ["JJK"], song: "Kaikai Kitan", num: 1, url: "https://animethemes.moe/video/JujutsuKaisen-OP1.webm" },
    { anime: "JUJUTSU KAISEN", alt: ["JJK"], song: "VIVID VICE", num: 2, url: "https://animethemes.moe/video/JujutsuKaisen-OP2.webm" },
    { anime: "JUJUTSU KAISEN", alt: ["JJK"], song: "Ao no Sumika", num: 3, url: "https://animethemes.moe/video/JujutsuKaisenS2-OP1.webm" },
    { anime: "JUJUTSU KAISEN", alt: ["JJK"], song: "SPECIALZ", num: 4, url: "https://animethemes.moe/video/JujutsuKaisenS2-OP2.webm" },

    // --- BLUE EXORCIST ---
    { anime: "BLUE EXORCIST", alt: ["AO NO EXORCIST"], song: "Core Pride", num: 1, url: "https://animethemes.moe/video/AoNoExorcist-OP1.webm" },
    { anime: "BLUE EXORCIST", alt: ["AO NO EXORCIST"], song: "In My World", num: 2, url: "https://animethemes.moe/video/AoNoExorcist-OP2.webm" },
    { anime: "BLUE EXORCIST", alt: ["AO NO EXORCIST"], song: "Itteki no Eikyou", num: 3, url: "https://animethemes.moe/video/AoNoExorcistS2-OP1-NCBD1080.webm" },
    { anime: "BLUE EXORCIST", alt: ["AO NO EXORCIST"], song: "Eye's Sentry", num: 4, url: "https://animethemes.moe/video/AoNoExorcistS3-OP1.webm" },

    // --- FIRE FORCE ---
    { anime: "FIRE FORCE", alt: ["ENEN"], song: "Inferno", num: 1, url: "https://animethemes.moe/video/EnenNoShouboutai-OP1-NCBD1080.webm" },
    { anime: "FIRE FORCE", alt: ["ENEN"], song: "MAYDAY", num: 2, url: "https://v.animethemes.moe/EnenNoShouboutai-OP2-NCBD1080.webm" },
    { anime: "FIRE FORCE", alt: ["ENEN"], song: "SPARK-AGAIN", num: 3, url: "https://animethemes.moe/video/EnenNoShouboutaiS2-OP1-NCBD1080.webm" },

    // --- TENSURA (SLIME) ---
    { anime: "TENSEI SHITARA SLIME", alt: ["TENSURA"], song: "Nameless Story", num: 1, url: "https://animethemes.moe/video/Tensura-OP1-NCBD1080.webm" },
    { anime: "TENSEI SHITARA SLIME", alt: ["TENSURA"], song: "Megurumono", num: 2, url: "https://animethemes.moe/video/Tensura-OP2-NCBD1080.webm" },
    { anime: "TENSEI SHITARA SLIME", alt: ["TENSURA"], song: "Storyteller", num: 3, url: "https://animethemes.moe/video/TensuraS2-OP1.webm" },
    { anime: "TENSEI SHITARA SLIME", alt: ["TENSURA"], song: "Like Flames", num: 4, url: "https://animethemes.moe/video/TensuraS2Part2-OP1.webm" },
    { anime: "TENSEI SHITARA SLIME", alt: ["TENSURA"], song: "PEACEKEEPER", num: 5, url: "https://animethemes.moe/video/TensuraS3-OP1.webm" },

    // --- DIVERS ---
    { anime: "VINLAND SAGA", alt: [], song: "MUKANJYO", num: 1, url: "https://animethemes.moe/video/VinlandSaga-OP1-NCBD1080.webm" },
    { anime: "VINLAND SAGA", alt: [], song: "Dark Crow", num: 2, url: "https://animethemes.moe/video/VinlandSaga-OP2-NCBD1080.webm" },
    { anime: "VINLAND SAGA", alt: [], song: "River", num: 3, url: "https://animethemes.moe/video/VinlandSagaS2-OP1.webm" },
    { anime: "CODE GEASS", alt: [], song: "COLORS", num: 1, url: "https://animethemes.moe/video/CodeGeass-OP1.webm" },
    { anime: "CYBERPUNK EDGERUNNERS", alt: [], song: "This Fffire", num: 1, url: "https://animethemes.moe/video/CyberpunkEdgerunners-OP1.webm" },
    { anime: "GACHIAKUTA", alt: [], song: "TBA", num: 1, url: "https://v.animethemes.moe/Gachiakuta-OP1.webm" },
    { anime: "UNDEAD UNLUCK", alt: [], song: "01", num: 1, url: "https://animethemes.moe/video/UndeadUnluck-OP1.webm" },
    { anime: "UNDEAD UNLUCK", alt: [], song: "Love Call", num: 2, url: "https://animethemes.moe/video/UndeadUnluck-OP2.webm" },
    { anime: "OVERLORD", alt: [], song: "Clattanoia", num: 1, url: "https://animethemes.moe/video/OverlordOVA-OP1.webm" }, // Note: Corrigé pour pointer vers le bon OP1
    { anime: "OVERLORD", alt: [], song: "HOLLOW HUNGER", num: 4, url: "https://animethemes.moe/video/OverlordS4-OP1.webm" },
    { anime: "BUNGO STRAY DOGS", alt: [], song: "Reason Living", num: 2, url: "https://animethemes.moe/video/BungouStrayDogsS2-OP1-BD1080.webm" },
    { anime: "TOWER OF GOD", alt: ["KAMI NO TOU"], song: "TOP", num: 1, url: "https://animethemes.moe/video/KamiNoTou-OP1-KO.webm" },
    { anime: "TOWER OF GOD", alt: ["KAMI NO TOU"], song: "RISE UP", num: 2, url: "https://animethemes.moe/video/KamiNoTouS2-OP1.webm" },
    { anime: "URUSEI YATSURA", alt: [], song: "Lum no Love Song", num: 1, url: "https://animethemes.moe/video/UruseiYatsura-OP1.webm" },
    { anime: "URUSEI YATSURA", alt: [], song: "Aiue", num: 2, url: "https://v.animethemes.moe/UruseiYatsura2022-OP1.webm" },
    { anime: "MOB PSYCHO 100", alt: [], song: "99", num: 1, url: "https://animethemes.moe/video/MobPsycho100-OP1.webm" },
    { anime: "MOB PSYCHO 100", alt: [], song: "99.9", num: 2, url: "https://animethemes.moe/video/MobPsycho100S2-OP1-BD1080.webm" },
    { anime: "MOB PSYCHO 100", alt: [], song: "1", num: 3, url: "https://animethemes.moe/video/MobPsycho100S3-OP1.webm" },
    { anime: "NO GAME NO LIFE", alt: ["NGNL"], song: "This Game", num: 1, url: "https://animethemes.moe/video/NoGameNoLife-OP1.webm" },
    { anime: "MADE IN ABYSS", alt: [], song: "Deep in Abyss", num: 1, url: "https://animethemes.moe/video/MadeInAbyss-OP2-NCBD1080.webm" }, // Note: Ajusté OP2 (Deep in Abyss est souvent OP2 en contexte BD)
    { anime: "MADE IN ABYSS", alt: [], song: "Katachi", num: 2, url: "https://animethemes.moe/video/MadeInAbyssS2-OP2.webm" },
    { anime: "TOUGEN ANKI", alt: [], song: "TBA", num: 1, url: "https://v.animethemes.moe/TougenAnki-OP1.webm" },
    { anime: "LINK CLICK", alt: [], song: "Dive Back In Time", num: 1, url: "https://animethemes.moe/video/ShiguangDailiren-OP1.webm" },
    { anime: "BUNNY GIRL SENPAI", alt: [], song: "Kimi no Sei", num: 1, url: "https://animethemes.moe/video/Aobuta-OP1-Lyrics.webm" },
    { anime: "WIND BREAKER", alt: [], song: "Zettai Reido", num: 1, url: "https://animethemes.moe/video/WindBreaker-OP1.webm" },
    { anime: "TENGOKU DAIMAKYOU", alt: [], song: "innocent arrogance", num: 1, url: "https://animethemes.moe/video/TengokuDaimakyou-OP1.webm" },
    { anime: "PARIPI KOUMEI", alt: ["YA BOY KONGMING"], song: "Chikichiki Banban", num: 1, url: "https://animethemes.moe/video/ParipiKoumei-OP1.webm" },
    { anime: "KEKKAI SENSEN", alt: ["BLOOD BLOCKADE"], song: "Hello, world!", num: 1, url: "https://animethemes.moe/video/KekkaiSensen-OP1.webm" },
    // Supprimé: Dragon Raja (demande utilisateur)
    { anime: "BEASTARS", alt: [], song: "Wild Side", num: 1, url: "https://animethemes.moe/video/Beastars-OP1-NCBD1080.webm" },
    { anime: "SUMMER TIME RENDERING", alt: [], song: "Hoshi ga Oyogu", num: 1, url: "https://animethemes.moe/video/SummertimeRender-OP1.webm" },
    { anime: "RANKING OF KINGS", alt: ["OUSAMA RANKING"], song: "BOY", num: 1, url: "https://animethemes.moe/video/OusamaRanking-OP1.webm" },
    { anime: "RE:ZERO", alt: [], song: "Redo", num: 1, url: "https://animethemes.moe/video/ReZero-OP1.webm" },
    { anime: "RE:ZERO", alt: [], song: "Paradisus-Paradoxum", num: 2, url: "https://animethemes.moe/video/ReZero-OP2.webm" },
    { anime: "RE:ZERO", alt: [], song: "Realize", num: 3, url: "https://animethemes.moe/video/ReZeroS2-OP1-NCBD1080.webm" },
    { anime: "RE:ZERO", alt: [], song: "Long shot", num: 4, url: "https://animethemes.moe/video/ReZeroS2Part2-OP1.webm" },
    { anime: "FATE/STAY NIGHT", alt: [], song: "disillusion", num: 1, url: "https://animethemes.moe/video/FateStayNight-OP1.webm" },
    { anime: "HELL'S PARADISE", alt: ["JIGOKURAKU"], song: "WORK", num: 1, url: "https://animethemes.moe/video/Jigokuraku-OP1.webm" },
    { anime: "FULLMETAL ALCHEMIST: BROTHERHOOD", alt: ["FMAB"], song: "Again", num: 1, url: "https://animethemes.moe/video/FullmetalAlchemistBrotherhood-OP1.webm" },
    { anime: "FULLMETAL ALCHEMIST: BROTHERHOOD", alt: ["FMAB"], song: "Hologram", num: 2, url: "https://animethemes.moe/video/FullmetalAlchemistBrotherhood-OP2.webm" },
    { anime: "FULLMETAL ALCHEMIST: BROTHERHOOD", alt: ["FMAB"], song: "Golden Time Lover", num: 3, url: "https://animethemes.moe/video/FullmetalAlchemistBrotherhood-OP3.webm" },
    { anime: "FULLMETAL ALCHEMIST: BROTHERHOOD", alt: ["FMAB"], song: "Period", num: 4, url: "https://animethemes.moe/video/FullmetalAlchemistBrotherhood-OP4.webm" },
    { anime: "FULLMETAL ALCHEMIST: BROTHERHOOD", alt: ["FMAB"], song: "Rain", num: 5, url: "https://animethemes.moe/video/FullmetalAlchemistBrotherhood-OP5.webm" },
    { anime: "TOKYO GHOUL", alt: [], song: "unravel", num: 1, url: "https://animethemes.moe/video/TokyoGhoul-OP1.webm" },
    { anime: "FULLMETAL ALCHEMIST", alt: ["FMA"], song: "Melissa", num: 1, url: "https://animethemes.moe/video/FullmetalAlchemist-OP1.webm" },
    { anime: "VIOLET EVERGARDEN", alt: [], song: "Sincerely", num: 1, url: "https://animethemes.moe/video/VioletEvergarden-OP1-Lyrics.webm" },
    { anime: "FATE/ZERO", alt: [], song: "oath sign", num: 1, url: "https://animethemes.moe/video/FateZero-OP1.webm" },
    { anime: "GINTAMA", alt: [], song: "Sakura Mitsutsuki", num: 13, url: "https://animethemes.moe/video/GintamaEnchousen-OP3-NCBD1080.webm" },
    { anime: "LES CARNETS DE L'APOTHICAIRE", alt: ["KUSURIYA NO HITORIGOTO"], song: "Hana ni Natte", num: 1, url: "https://v.animethemes.moe/KusuriyaNoHitorigoto-OP1.webm" },
    { anime: "LES CARNETS DE L'APOTHICAIRE", alt: ["KUSURIYA NO HITORIGOTO"], song: "Ambivalent", num: 2, url: "https://v.animethemes.moe/KusuriyaNoHitorigoto-OP2.webm" },
    { anime: "HUNTER X HUNTER", alt: ["HXH"], song: "departure!", num: 1, url: "https://animethemes.moe/video/HunterHunter2011-OP1.webm" },
    { anime: "DANDADAN", alt: [], song: "Otonoke", num: 1, url: "https://animethemes.moe/video/Dandadan-OP1.webm" },
    { anime: "ZOM 100", alt: [], song: "Song of the Dead", num: 1, url: "https://animethemes.moe/video/Zom100-OP1.webm" },
    { anime: "CLASSROOM OF THE ELITE", alt: ["COTE"], song: "Caste Room", num: 1, url: "https://animethemes.moe/video/YoukosoZitsu-OP1-NCBD1080.webm" },
    { anime: "MUSHOKU TENSEI", alt: [], song: "Tabibito no Uta", num: 1, url: "https://animethemes.moe/video/MushokuTensei-OP1.webm" },
    { anime: "SHANGRI-LA FRONTIER", alt: [], song: "BROKEN GAMES", num: 1, url: "https://animethemes.moe/video/ShangrilaFrontier-OP1.webm" },
    { anime: "THE DANGERS IN MY HEART", alt: ["BOKUYABA"], song: "Shayo", num: 1, url: "https://animethemes.moe/video/Bokuyaba-OP1.webm" },
    { anime: "YOUR LIE IN APRIL", alt: ["SHIGATSU"], song: "Hikaru Nara", num: 1, url: "https://animethemes.moe/video/KimiUso-OP1.webm" },
    { anime: "WOTAKOI", alt: [], song: "Fiction", num: 1, url: "https://animethemes.moe/video/WotaKoi-OP1v3.webm" },
    { anime: "RISING OF THE SHIELD HERO", alt: ["TATE NO YUUSHA"], song: "RISE", num: 1, url: "https://animethemes.moe/video/ShieldHero-OP1-NCBD1080.webm" },
    { anime: "KAGUYA-SAMA", alt: [], song: "Love Dramatic", num: 1, url: "https://v.animethemes.moe/KaguyaSamaWaKokurasetai-OP1.webm" },
    { anime: "DEADMAN WONDERLAND", alt: [], song: "One Reason", num: 1, url: "https://animethemes.moe/video/DeadmanWonderland-OP1.webm" },
    { anime: "NORAGAMI", alt: [], song: "Goya no Machiawase", num: 1, url: "https://animethemes.moe/video/Noragami-OP1.webm" },
    { anime: "BOCCHI THE ROCK", alt: [], song: "Seishun Complex", num: 1, url: "https://animethemes.moe/video/BocchiTheRock-OP1.webm" },
    { anime: "FRIEREN", alt: [], song: "Yuusha", num: 1, url: "https://v.animethemes.moe/SousouNoFrieren-OP1.webm" },
    { anime: "HORIMIYA", alt: [], song: "Iro Kousui", num: 1, url: "https://v.animethemes.moe/Horimiya-OP1.webm" },
    { anime: "MAGI", alt: [], song: "V.I.P", num: 1, url: "https://animethemes.moe/video/MagiLabyrinthOfMagic-OP1.webm" },
    { anime: "GTO", alt: [], song: "Driver's High", num: 1, url: "https://animethemes.moe/video/GreatTeacherOnizuka-OP1.webm" },
    { anime: "AKAME GA KILL", alt: [], song: "Skyreach", num: 1, url: "https://animethemes.moe/video/AkameGaKill-OP1.webm" },
    { anime: "MASHLE", alt: [], song: "Knock Out", num: 1, url: "https://animethemes.moe/video/Mashle-OP1.webm" },
    { anime: "TOMODACHI GAME", alt: [], song: "Double Shuffle", num: 1, url: "https://animethemes.moe/video/TomodachiGame-OP1.webm" },
    { anime: "LINK CLICK", alt: [], song: "Dive Back In Time", num: 1, url: "https://animethemes.moe/video/ShiguangDailiren-OP1.webm" },
    { anime: "RAGNA CRIMSON", alt: [], song: "ROAR", num: 1, url: "https://animethemes.moe/video/RagnaCrimson-OP1.webm" },
    { anime: "SOLO LEVELING", alt: [], song: "LEveL", num: 1, url: "https://animethemes.moe/video/SoloLeveling-OP1.webm" },
    { anime: "SERIAL EXPERIMENTS LAIN", alt: [], song: "Duvet", num: 1, url: "https://animethemes.moe/video/SerialExperimentsLain-OP1.webm" },
    { anime: "DOMESTIC GIRLFRIEND", alt: [], song: "Kawaki wo Ameku", num: 1, url: "https://animethemes.moe/video/DomesticNaKanojo-OP1-NCBD1080.webm" },
    { anime: "KOKKOKU", alt: [], song: "Flashback", num: 1, url: "https://animethemes.moe/video/Kokkoku-OP1.webm" },
    { anime: "KAIJU NO. 8", alt: [], song: "Abyss", num: 1, url: "https://animethemes.moe/video/Kaijuu8Gou-OP1.webm" },
    { anime: "SERAPH OF THE END", alt: ["OWARI NO SERAPH"], song: "X.U.", num: 1, url: "https://animethemes.moe/video/OwariNoSeraph-OP1.webm" },
    { anime: "KONOSUBA", alt: [], song: "fantastic dreamer", num: 1, url: "https://animethemes.moe/video/Konosuba-OP1.webm" },
    { anime: "KOMI CAN'T COMMUNICATE", alt: [], song: "Cinderella", num: 1, url: "https://animethemes.moe/video/KomiSanWaKomyushouDesu-OP1.webm" },
    { anime: "DARLING IN THE FRANXX", alt: [], song: "KISS OF DEATH", num: 1, url: "https://v.animethemes.moe/DarlingInTheFranXX-OP1.webm" },
    { anime: "AO HARU RIDE", alt: [], song: "Sekai wa Koi ni Ochiteiru", num: 1, url: "https://animethemes.moe/video/AoHaruRide-OP1.webm" },
    { anime: "TOKYO REVENGERS", alt: [], song: "Cry Baby", num: 1, url: "https://animethemes.moe/video/TokyoRevengers-OP1.webm" },
    { anime: "BASTARD!!", alt: [], song: "Bloody Power Fame", num: 1, url: "https://animethemes.moe/video/Bastard2022-OP1.webm" },
    { anime: "BLUE BOX", alt: [], song: "Same Blue", num: 1, url: "https://animethemes.moe/video/AoNoHako-OP1.webm" },
    { anime: "PLASTIC MEMORIES", alt: [], song: "Ring of Fortune", num: 1, url: "https://animethemes.moe/video/PlasticMemories-OP1.webm" },
    { anime: "MEDALIST", alt: [], song: "TBA", num: 1, url: "https://v.animethemes.moe/Medalist-OP1.webm" },
    { anime: "BLACK BUTLER", alt: ["KUROSHITSUJI"], song: "Monochrome no Kiss", num: 1, url: "https://v.animethemes.moe/Kuroshitsuji-OP1.webm" },
    { anime: "KILL LA KILL", alt: [], song: "Sirius", num: 1, url: "https://animethemes.moe/video/KillLaKill-OP1.webm" },
    { anime: "ASSASSINATION CLASSROOM", alt: ["ANSATSU KYOUSHITSU"], song: "Seishun Satsubatsuron", num: 1, url: "https://animethemes.moe/video/AnsatsuKyoushitsu-OP1.webm" },
    { anime: "CALL OF THE NIGHT", alt: ["YOFUKASHI NO UTA"], song: "Daten", num: 1, url: "https://animethemes.moe/video/YofukashiNoUta-OP1.webm" },
    { anime: "ELFEN LIED", alt: [], song: "Lilium", num: 1, url: "https://animethemes.moe/video/ElfenLied-OP1.webm" },
    { anime: "FREE!", alt: [], song: "Rage on", num: 1, url: "https://animethemes.moe/video/Free-OP1-NCBD1080.webm" },
    { anime: "STEINS;GATE", alt: [], song: "Hacking to the Gate", num: 1, url: "https://animethemes.moe/video/SteinsGate-OP1.webm" },
    { anime: "ERASED", alt: ["BOKU DAKE GA INAI MACHI"], song: "Re:Re:", num: 1, url: "https://animethemes.moe/video/BokuDakeGaInaiMachi-OP1.webm" },
    { anime: "SOUL EATER", alt: [], song: "resonance", num: 1, url: "https://animethemes.moe/video/SoulEater-OP1.webm" },
    { anime: "SAKAMOTO DAYS", alt: [], song: "TBA", num: 1, url: "https://v.animethemes.moe/SakamotoDays-OP1.webm" },
    { anime: "RAINBOW", alt: [], song: "We're not alone", num: 1, url: "https://animethemes.moe/video/Rainbow-OP1.webm" },
    { anime: "COWBOY BEBOP", alt: [], song: "Tank!", num: 1, url: "https://animethemes.moe/video/CowboyBebop-OP1.webm" },
    { anime: "YURI!!! ON ICE", alt: [], song: "History Maker", num: 1, url: "https://animethemes.moe/video/YuriOnIce-OP1.webm" },
    { anime: "A CERTAIN SCIENTIFIC ACCELERATOR", alt: [], song: "Shadow is the Light", num: 1, url: "https://animethemes.moe/video/ToaruKagakuNoAccelerator-OP1-NCBD1080.webm" },
    { anime: "GUILTY CROWN", alt: [], song: "My Dearest", num: 1, url: "https://animethemes.moe/video/GuiltyCrown-OP2.webm" }, // Note: Corrigé vers OP2 souvent associé à My Dearest
    { anime: "KAKEGURUI", alt: ["GAMBLING SCHOOL"], song: "Deal with the devil", num: 1, url: "https://animethemes.moe/video/Kakegurui-OP1-NCBD1080.webm" },
    { anime: "DEATH PARADE", alt: [], song: "Flyers", num: 1, url: "https://animethemes.moe/video/DeathParade-OP1.webm" },
    { anime: "BANANA FISH", alt: [], song: "found & lost", num: 1, url: "https://animethemes.moe/video/BananaFish-OP1-Lyrics.webm" },
    { anime: "ANGEL BEATS!", alt: [], song: "My Soul, Your Beats!", num: 1, url: "https://animethemes.moe/video/AngelBeats-OP1.webm" },
    { anime: "ROSHIDERE", alt: [], song: "1-ban Kagayaku Hoshi", num: 1, url: "https://animethemes.moe/video/Roshidere-OP1.webm" },
    { anime: "KIMI NO TODOKE", alt: [], song: "Kimi no Todoke", num: 1, url: "https://animethemes.moe/video/KimiNiTodoke-OP1.webm" },
    { anime: "ONE PUNCH MAN", alt: ["OPM"], song: "THE HERO !!", num: 1, url: "https://v.animethemes.moe/OnePunchMan-OP1.webm" },
    { anime: "MY DRESS-UP DARLING", alt: ["SONO BISQUE DOLL"], song: "Sansan Days", num: 1, url: "https://animethemes.moe/video/BisqueDoll-OP1.webm" },
    { anime: "NO. 6", alt: [], song: "Spell", num: 1, url: "https://animethemes.moe/video/No6-OP1.webm" },
    { anime: "TRIGUN STAMPEDE", alt: [], song: "TOMBI", num: 1, url: "https://animethemes.moe/video/TrigunStampede-OP1.webm" }
];
