// --- COVERS DES ALBUMS ---
export const ALBUM_COVERS = {
    "Chambre 140": "https://i.postimg.cc/GpJd8WhY/ab67616d0000b2735f47f03829e4df052424712c.jpg",
    "2069": "https://i.postimg.cc/G2wTdwgJ/0x1900_000000_80_0_0.jpg",
    "Enna": "https://i.postimg.cc/bJcSpcV0/0x1900_000000_80_0_0_(1).jpg",
    "Mental": "https://i.postimg.cc/NMq2BqCH/0x1900_000000_80_0_0_(2).jpg",
    "Polak": "https://i.postimg.cc/W3LqTLYh/0x1900_000000_80_0_0_(3).jpg",
    "Platinum": "https://i.postimg.cc/bJcSpcVd/0x1900_000000_80_0_0_(4).jpg",
    "Ténébreux": "https://i.postimg.cc/TwM5fMNw/0x1900_000000_80_0_0_(5).jpg",
    "Feat.": "https://i.postimg.cc/bv2S7Ng2/549462567_1359332145554525_4081579609646448260_n.jpg",
    "Single": "https://i.postimg.cc/FR5kN5CH/plk_concert_paris_zenith_800x800.jpg"
};

// --- DISCOGRAPHIE COMPLÈTE CORRIGÉE ---
export const PLK_RAW_DISCOGRAPHY = {
    "Chambre 140": [
        // Titres originaux Chambre 140
        { title: "Chambre 140", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Chambre%20140.mp3" },
        { title: "EA7", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20EA7.mp3" },
        { title: "Flash", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Flash.mp3" },
        { title: "Gare du Nord", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Gare%20du%20Nord.mp3" },
        { title: "Il pleut à Paris", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Il%20pleut%20%C3%A0%20Paris.mp3" },
        { title: "Mignon tout plein", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Mignon%20tout%20plein.mp3" },
        { title: "Périph", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20P%C3%A9riph.mp3" },
        { title: "Sun", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Sun.mp3" },
        { title: "Ça fait longtemps", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20%C3%87a%20fait%20longtemps.mp3" },
        { title: "Ça mène à rien", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Gazo%20-%20%C3%87a%20m%C3%A8ne%20%C3%A0%20rien.mp3" },
        { title: "En mieux", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Hamza%20-%20En%20mieux.mp3" },
        { title: "Faut pas", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Jul%20-%20Faut%20pas.mp3" },
        { title: "La nuit", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20TIF%20-%20La%20nuit.mp3" },
        { title: "Chouchou", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Vacra%20-%20Chouchou.mp3" },
        // Corrections ajoutées à Chambre 140
        { title: "Ptain", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Ptain.mp3" },
        { title: "La vraie vie", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20La%20vraie%20vie.mp3" },
        { title: "Attentat", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20OBOY%20-%20Attentat.mp3" },
        { title: "Dangereux", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Dangereux.mp3" },
        { title: "J'attends", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20J%27attends.mp3" },
        { title: "Onana", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Onana.mp3" },
        { title: "Avec les miens", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Avec%20les%20miens.mp3" },
        { title: "Bikini Bottom", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Bikini%20Bottom.mp3" },
        { title: "A l'envers", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20A%20l%27envers.mp3" },
        { title: "Mon poto", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Mon%20poto.mp3" },
        { title: "Une pêche une patate", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Une%20p%C3%A9che%20une%20patate.mp3" },
        { title: "1Eu", album: "Chambre 140", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%201%E2%82%AC%C2%A0%201Eu.mp3" }
    ],
    "2069 (EP)": [
        // Titres originaux 2069
        { title: "Demain", album: "2069", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Demain.mp3" },
        { title: "Décembre", album: "2069", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20D%C3%A9cembre.mp3" },
        { title: "Nouvelles", album: "2069", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Nouvelles.mp3" },
        { title: "Panama Bende", album: "2069", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Panama%20Bende.mp3" }, 
        { title: "10 minutes", album: "2069", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Dinos%20-%2010%20minutes.mp3" },
        { title: "77", album: "2069", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Kerchak%20-%2077.mp3" },
        // Corrections ajoutées à 2069
        { title: "Pelo", album: "2069", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Pelo.mp3" },
        { title: "Pas de sentiments", album: "2069", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Pas%20de%20sentiments.mp3" },
        { title: "Cash", album: "2069", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Cash.mp3" }
    ],
    "Enna": [
        // Titres originaux Enna
        { title: "Pilote", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Hamza%20-%20Pilote%20%28feat.%20Hamza%29.mp3" },
        { title: "On sait jamais", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Niska%20-%20On%20sait%20jamais%20%28feat.%20Niska%29.mp3" },
        { title: "Chandon et Moët", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Heuss%20L%27enfoir%C3%A9%20-%20Chandon%20et%20Mo%C3%ABt%20%28feat.%20Heuss%20l%27Enfoir%C3%A9%29.mp3" },
        { title: "Toutes générations", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Rim%27K%20-%20Toutes%20g%C3%A9n%C3%A9rations%20%28feat.%20Rim%27K%29.mp3" },
        { title: "Au fond d'ma tête", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Au%20fond%20d%27ma%20t%C3%AAte.mp3" },
        { title: "Billet d'20", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Billet%20d%2720.mp3" },
        { title: "Dans les clips", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Dans%20les%20clips.mp3" },
        { title: "Pourtant", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Pourtant.mp3" },
        { title: "Mamie", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Mamie.mp3" },
        { title: "Alleluia", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Alleluia.mp3" },
        { title: "C'est mort", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20C%27est%20mort.mp3" },
        { title: "Les comptes", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Les%20comptes.mp3" },
        { title: "Bénef", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20B%C3%A9nef.mp3" },
        { title: "Terrible", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Terrible.mp3" },
        { title: "3 en 1", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%203%20en%201.mp3" },
        { title: "La vie c'est marrant", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20La%20vie%20c%27est%20marrant.mp3" },
        { title: "Calme", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Calme.mp3" },
        { title: "A la base", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20A%20la%20base.mp3" },
        { title: "Boost", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Boost.mp3" },
        { title: "En ville", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20SDM%20-%20En%20ville.mp3" },
        { title: "Hubert et Saïd", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Hubert%20et%20Sa%C3%AFd.mp3" },
        { title: "Perdu", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Perdu.mp3" },
        // Corrections ajoutées à Enna (provenant de Boost ou d'ailleurs)
        { title: "Si ça marche plus", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Si%20%C3%A7a%20marche%20plus.mp3" },
        { title: "Dégaine de bandit", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20D%C3%A9gaine%20de%20bandit.mp3" },
        { title: "Amérique", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Am%C3%A9rique.mp3" },
        { title: "R.A.F", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20R.A.F.mp3" },
        { title: "10 Millions", album: "Enna", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%2010%20Millions.mp3" }
    ],
    "Mental": [
        // Titres originaux Mental
        { title: "Un peu de haine", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Un%20peu%20de%20haine.mp3" },
        { title: "Hola", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Hola.mp3" },
        { title: "Travailler", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Travailler.mp3" },
        { title: "Nana", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Nana.mp3" },
        { title: "Meilleur cauchemar", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Meilleur%20cauchemar.mp3" },
        { title: "Tout recommencer", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Tessa%20B.%C2%A0%20-%20Tout%20recommencer%20%28feat.%20Tessa%20B%29.mp3" },
        { title: "V2V", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20V2V.mp3" },
        { title: "Corazon", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Aladin%20135%20-%20Corazon%20%28feat.%20Aladin%20135%29.mp3" },
        { title: "Cartelo", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Maes%20-%20Cartelo%20%28feat.%20Maes%29.mp3" },
        { title: "Toute l'année", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Timal%20-%20Toute%20l%27ann%C3%A9e%20%28feat.%20Timal%29.mp3" },
        { title: "Mental", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Mental.mp3" },
        { title: "Ma génération", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Ma%20g%C3%A9n%C3%A9ration.mp3" },
        { title: "Temps perdu", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Temps%20perdu.mp3" },
        { title: "TT", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20TT.mp3" },
        { title: "RS3", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20RS3.mp3" },
        { title: "Incontrolables", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20SCH%20-%20Incontrolables.mp3" },
        // Corrections ajoutées à Mental
        { title: "Problèmes", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Probl%C3%A8mes.mp3" },
        { title: "Le P", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Le%20P.mp3" },
        { title: "Arai", album: "Mental", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Arai.mp3" }
    ],
    "Polak": [
        // Titres originaux Polak
        { title: "Monégasque", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Mon%C3%A9gasque.mp3" },
        { title: "Polak", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Polak.mp3" },
        { title: "Hier", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20SCH%20-%20Hier%20%28feat.%20SCH%29.mp3" },
        { title: "Waow", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Nekfeu%20-%20Waow%20%28feat.%20Nekfeu%29.mp3" },
        { title: "Dingue", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Dingue.mp3" },
        { title: "250", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20250.mp3" },
        { title: "Sans suite", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Sans%20suite.mp3" },
        { title: "Bunkoeur", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Bunkoeur.mp3" },
        { title: "Idiote", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Idiote.mp3" },
        { title: "Le sel", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Le%20sel.mp3" },
        { title: "Gozier", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Paluch%20-%20Gozier%20%28feat.%20Paluch%29.mp3" },
        { title: "Ils nous comprennent pas", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Ils%20nous%20comprennent%20pas.mp3" },
        { title: "Olcho Gvng", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Olcho%20Gvng.mp3" },
        { title: "Weed", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Weed.mp3" },
        { title: "Séparer", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20S%C3%A9parer.mp3" },
        { title: "260", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20260.mp3" },
        { title: "POL AK", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20POL-AK.mp3" },
        { title: "Intro", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Intro.mp3" },
        { title: "Intr100000", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Intr100000.mp3" },
        // Corrections ajoutées à Polak
        { title: "Émotif", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20%C3%89motif%20%28Booska%201H%29.mp3" },
        { title: "Enfant du hall", album: "Polak", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Enfant%20du%20hall.mp3" }
    ],
    "Platinum": [
        // Titres originaux Platinum
        { title: "Pas les mêmes", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Pas%20les%20m%C3%AAmes.mp3" },
        { title: "A A A", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20A%20A%20A.mp3" },
        { title: "Dis moi oui", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Dis-moi%20oui.mp3" },
        { title: "Copine", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Copine.mp3" },
        { title: "Platinum", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Platinum.mp3" },
        { title: "Izé", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Iz%C3%A9.mp3" },
        { title: "Go", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Krisy%20-%20Go%20%28feat.%20Krisy%29.mp3" },
        { title: "Pas ce soir", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Krisy%20-%20Pas%20ce%20soir%20%28feat.%20Krisy%29.mp3" },
        { title: "Pas besoin", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Pas%20besoin.mp3" },
        { title: "C'est grave", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20C%27est%20grave.mp3" },
        { title: "High", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20High.mp3" },
        { title: "Mentalité", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Mentalit%C3%A9.mp3" },
        { title: "Niveau", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Niveau.mp3" },
        { title: "Colis piégés", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Lefa%20-%20Colis%20pi%C3%A9g%C3%A9s%20%28feat.%20Lefa%29.mp3" },
        { title: "Homies", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Homies.mp3" },
        { title: "Amigo", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Amigo.mp3" },
        { title: "Skuu", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%2C%20Krisy%20-%20Skuu%20%28feat.%20Krisy%29.mp3" },
        { title: "Flamenco", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Flamenco%20-%20Bonus%20Track.mp3" },
        // Corrections ajoutées à Platinum
        { title: "La rue", album: "Platinum", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20La%20rue.mp3" }
    ],
    "Ténébreux": [
        // Titres originaux Ténébreux
        { title: "Ténébreux", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20T%C3%A9n%C3%A9breux.mp3" },
        { title: "All Night", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20All%20Night.mp3" },
        { title: "Du mal", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Du%20mal.mp3" },
        { title: "Casino", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Casino.mp3" },
        { title: "Yeux", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Yeux.mp3" },
        { title: "Plata O Plomo", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Plata%20O%20Plomo.mp3" },
        { title: "Shérif", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Sh%C3%A9rif.mp3" },
        { title: "Hall", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Hall.mp3" },
        { title: "Juste Un Petit Peu", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Juste%20Un%20Petit%20Peu.mp3" },
        { title: "Fin de mois", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Fin%20de%20mois.mp3" },
        // Corrections ajoutées à Ténébreux
        { title: "Faut croire", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Faut%20croire.mp3" },
        { title: "Amigo", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Amigo.mp3" },
        { title: "Avec moi", album: "Ténébreux", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20Avec%20moi.mp3" }
    ],
    "Apparitions / Featurings": [
        { title: "Aminata", album: "Feat. 13 Block", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/13%20Block%2C%20PLK%20-%20Aminata%20%28feat.%20PLK%29.mp3" },
        { title: "10", album: "Feat. 404Billy", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/404Billy%2C%20PLK%20-%2010.mp3" },
        { title: "All Day", album: "Feat. Aladin 135", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Aladin%20135%2C%20PLK%20-%20All%20Day.mp3" },
        { title: "Hiver", album: "Feat. Aladin 135", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Aladin%20135%2C%20PLK%2C%20Lesram%20-%20Hiver.mp3" },
        { title: "Tableau de bord", album: "Feat. Alonzo", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Alonzo%2C%20PLK%20-%20Tableau%20de%20bord.mp3" },
        { title: "Fisheye", album: "Feat. Bekar", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Bekar%2C%20PLK%20-%20Fisheye%20%28feat.%20PLK%29.mp3" },
        { title: "Arriba", album: "Feat. Caballero", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Caballero%2C%20PLK%20-%20Arriba.mp3" },
        { title: "Des fois", album: "Feat. Dadju", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Dadju%2C%20PLK%20-%20Des%20fois.mp3" },
        { title: "Parle moi", album: "Feat. Dadju", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Dadju%2C%20PLK%20-%20Parle-moi.mp3" },
        { title: "Saigne", album: "Feat. Dadju", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Dadju%2C%20PLK%20-%20Saigne.mp3" },
        { title: "XbarV", album: "Feat. Dinor", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Dinor%20rdt%2C%20PLK%20-%20XbarV%20%28feat.%20PLK%29.mp3" },
        { title: "Mondeo", album: "Feat. Doums", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Doums%2C%20PLK%20-%20Mondeo%20%28feat.%20PLK%29.mp3" },
        { title: "BNB", album: "Feat. Enima", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Enima%2C%20PLK%20-%20BNB.mp3" },
        { title: "Quand tout s'enflamme", album: "Feat. Georgio", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Georgio%2C%20PLK%20-%20Quand%20tout%20s%27enflamme.mp3" },
        { title: "Astrid", album: "Feat. JRK 19", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/JRK%2019%2C%20PLK%20-%20Astrid.mp3" },
        { title: "Postiché", album: "Feat. Jul", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/%C2%AB%20POSTICH%C3%89%20%C2%BB%20JUL%20%26%20PLK%20AU%20STADE%20DE%20FRANCE.mp3" },
        { title: "ALICANTE", album: "Feat. Karmen", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Karmen%2C%20PLK%20-%20ALICANTE.mp3" },
        { title: "Pas bien", album: "BO En Passant Pécho", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Kore%2C%20PLK%20-%20Pas%20bien%20-%20Extrait%20de%20la%20BO%20de%20%C2%AB%20En%20Passant%20P%C3%A9cho%20%C2%BB.mp3" },
        { title: "Ledger", album: "Feat. Lacrim", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Lacrim%2C%20PLK%20-%20Ledger%20%28feat.%20PLK%29.mp3" },
        { title: "230", album: "Feat. Lefa", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Lefa%2C%20PLK%20-%20230%20%28feat.%20PLK%29.mp3" },
        { title: "100X", album: "Feat. Lesram", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Lesram%2C%20PLK%20-%20100X%20%28feat.%20PLK%29.mp3" },
        { title: "Avec le temps", album: "Feat. Lesram", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Lesram%2C%20PLK%20-%20Avec%20le%20temps%20%28feat.%20PLK%29.mp3" },
        { title: "Train de vie", album: "Feat. Leto", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Leto%2C%20PLK%20-%20Train%20de%20vie%20%28feat.%20PLK%29.mp3" },
        { title: "4MOTION", album: "Feat. Maes", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Maes%2C%20PLK%20-%204MOTION.mp3" },
        { title: "Grosses Sommes", album: "Feat. Matou", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Matou%2C%20PLK%20-%20Grosses%20Sommes.mp3" },
        { title: "Jamais", album: "Feat. Mister V", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Mister%20V%2C%20PLK%20-%20Jamais.mp3" },
        { title: "Lambo", album: "Feat. Mister V", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Mister%20V%2C%20PLK%20-%20Lambo.mp3" },
        { title: "Zion", album: "Feat. Nemir", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Nemir%2C%20PLK%20-%20Zion.mp3" },
        { title: "Nuage qui passe", album: "Feat. Nessbeal", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Nessbeal%2C%20PLK%20-%20Nuage%20qui%20passe.mp3" },
        { title: "ON FAIT LES CHOSES", album: "Feat. Niaks", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Niaks%2C%20PLK%20-%20ON%20FAIT%20LES%20CHOSES.mp3" },
        { title: "Fils 2", album: "Feat. Niro", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Niro%2C%20PLK%20-%20Fils%202.mp3" },
        { title: "Vieilles Gueules", album: "Feat. Ormaz", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Ormaz%2C%20PLK%20-%20Vieilles%20Gueules.mp3" },
        { title: "Comme à l'ancienne", album: "Feat. RK", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/RK%2C%20PLK%20-%20Comme%20%C3%A0%20l%27ancienne.mp3" },
        { title: "Cosmos", album: "Feat. Rim'K", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Rim%27K%2C%20PLK%20-%20Cosmos.mp3" },
        { title: "Jack Fuego", album: "Feat. SDM", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/SDM%2C%20PLK%20-%20Jack%20Fuego.mp3" },
        { title: "Le bruit des applaudissements", album: "Feat. SDM", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/SDM%2C%20PLK%20-%20Le%20bruit%20des%20applaudissements.mp3" },
        { title: "Des années", album: "Feat. Shtar Ac", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Shtar%20Academy%2C%20PLK%2C%20Ryan%2C%20Perkiz%20-%20Des%20ann%C3%A9es.mp3" },
        { title: "Faux Paradis", album: "Feat. Soprano", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Soprano%2C%20PLK%20-%20Faux%20Paradis.mp3" },
        { title: "Petrouchka", album: "Feat. Soso Maness", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Soso%20Maness%2C%20PLK%20-%20Petrouchka%20%28feat.%20PLK%29.mp3" },
        { title: "Allez", album: "Feat. Soso Maness", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Soso%20Maness%2C%20PLK%2C%20Naps%20-%20Allez%20%28feat.%20PLK%20%26%20Naps%29.mp3" },
        { title: "Promis", album: "Feat. Timal", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Timal%2C%20PLK%20-%20Promis%20%28feat.%20PLK%29.mp3" },
        { title: "Sorry", album: "Feat. Tsew The Kid", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Tsew%20The%20Kid%2C%20PLK%20-%20%E2%81%B9%20Sorry.mp3" },
        { title: "Confidences", album: "Feat. Vacra", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Vacra%2C%20PLK%20-%20Confidences.mp3" },
        { title: "En pétard", album: "Feat. Werenoi", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Werenoi%2C%20PLK%20-%20En%20p%C3%A9tard.mp3" },
        { title: "Escorte", album: "Feat. Werenoi", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Werenoi%2C%20PLK%20-%20Escorte.mp3" },
        { title: "Mec de cité", album: "Feat. Yaro", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Yaro%2C%20Ninho%2C%20PLK%20-%20Mec%20de%20cit%C3%A9.mp3" },
        { title: "Salut", album: "Feat. Yaro", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Yaro%2C%20PLK%20-%20Salut.mp3" },
        { title: "Les jolies filles", album: "Feat. Zamdane", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Zamdane%2C%20PLK%20-%20Les%20jolies%20filles.mp3" },
        { title: "Piou Piou", album: "Feat. Zeu", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Zeu%2C%20PLK%2C%20Ormaz%20-%20Piou%20Piou.mp3" },
        { title: "Tu vois comment", album: "Feat. Zkr", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/Zkr%2C%20PLK%20-%20Tu%20vois%20comment%20.mp3" }
    ],
    "Singles / Hors Album": [
        { title: "Règlement Freestyle #17", album: "Freestyle", url: "https://storage.googleapis.com/blind-test-red-empire/Plk/PLK%20-%20R%C3%A8glement%20Freestyle%20%2317.mp3" }
    ]
};
