export const TIAKOLA_RAW_DISCOGRAPHY = {
    "BDLM Vol. 1": [
        { title: "1ntro'p", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - 1ntro'p.{ext}.mp3" },
        { title: "2009'", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - 2009'.{ext}.mp3" },
        { title: "CABREL", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - CABREL.{ext}.mp3" },
        { title: "CATIMINI", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - CATIMINI.{ext}.mp3" },
        { title: "CODE 187", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - CODE 187.{ext}.mp3" },
        { title: "FAST LIFE & FAMILLE", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - FAST LIFE & FAMILLE.{ext}.mp3" },
        { title: "FORMIDABLE", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - FORMIDABLE.{ext}.mp3" },
        { title: "GRAND PRIX", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - GRAND PRIX.{ext}.mp3" },
        { title: "HUMAN WEAKNESS", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - HUMAN WEAKNESS.{ext}.mp3" },
        { title: "MANON B (Brazilian Remix)", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - MANON B (feat. Ryflo, Oskoow & MC Cebezinho) - Brazilian Remix.{ext}.mp3" },
        { title: "MANON B", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - MANON B.{ext}.mp3" },
        { title: "MBIFE", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - MBIFE.{ext}.mp3" },
        { title: "Mayday", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Mayday.{ext}.mp3" },
        { title: "NO LIMIT", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - NO LIMIT.{ext}.mp3" },
        { title: "P&LOVÉ", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - P&LOVÉ.{ext}.mp3" },
        { title: "PING PONG", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - PING PONG.{ext}.mp3" },
        { title: "PLAISIR NOCIF", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - PLAISIR NOCIF.{ext}.mp3" },
        { title: "PONA NINI", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - PONA NINI.{ext}.mp3" },
        { title: "PROTECT", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - PROTECT.{ext}.mp3" },
        { title: "PSYCHOLOGIQUE", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - PSYCHOLOGIQUE.{ext}.mp3" },
        { title: "R.I.Peace", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - R.I.Peace.{ext}.mp3" },
        { title: "RESTE-LÀ", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - RESTE-LÀ.{ext}.mp3" },
        { title: "SOLO", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - SOLO (feat. La Fève).{ext}.mp3" },
        { title: "STATION", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - STATION.{ext}.mp3" },
        { title: "STELLAR", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - STELLAR.{ext}.mp3" },
        { title: "T.I.A", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - T.I.A.{ext}.mp3" },
        { title: "X", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - X.{ext}.mp3" },
        { title: "Y.J (C'EST KO)", album: "BDLM Vol. 1", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Y.J (C'EST KO).{ext}.mp3" }
    ],
    "Mélo": [
        { title: "1h55", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - 1h55.{ext}.mp3" },
        { title: "Arsenik", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Arsenik.{ext}.mp3" },
        { title: "Atasanté (feat. Hamza)", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Atasanté (feat. Hamza).{ext}.mp3" },
        { title: "#BÂTIMENT1", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - #BÂTIMENT1.{ext}.mp3" },
        { title: "Coucher de soleil", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Coucher de soleil.{ext}.mp3" },
        { title: "DERNIÈRE DANSE", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - DERNIÈRE DANSE.{ext}.mp3" },
        { title: "Étincelle - Maradona", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Étincelle - Maradona.{ext}.mp3" },
        { title: "G.A.N.G.", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - G.A.N.G.{ext}.mp3" },
        { title: "Gasolina (feat. Rsko)", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Gasolina (feat. Rsko).{ext}.mp3" },
        { title: "La clé", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - La clé.{ext}.mp3" },
        { title: "M3lo", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - M3lo.{ext}.mp3" },
        { title: "Meuda", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Meuda.{ext}.mp3" },
        { title: "Mise en garde", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Mise en garde.{ext}.mp3" },
        { title: "Mode AV (feat. Niska & Gazo)", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Mode AV (feat. Niska & Gazo).{ext}.mp3" },
        { title: "Parapluie", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Parapluie.{ext}.mp3" },
        { title: "Riri No camera", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Riri  No camera.{ext}.mp3" },
        { title: "Roro (feat. SDM)", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Roro (feat. SDM).{ext}.mp3" },
        { title: "Sans nouvelle", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Sans nouvelle.{ext}.mp3" },
        { title: "Si j'savais", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Si j'savais.{ext}.mp3" },
        { title: "Soza", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Soza.{ext}.mp3" },
        { title: "#TT", album: "Mélo", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - #TT.{ext}.mp3" }
    ],
    "La Mélo est Gangx": [
        { title: "200K", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - 200K.{ext}.mp3" },
        { title: "2434", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - 2434.{ext}.mp3" },
        { title: "A.V.S.D", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - A.V.S.D.{ext}.mp3" },
        { title: "AFRIKANBADMAN", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - AFRIKANBADMAN.{ext}.mp3" },
        { title: "AMBITIONS", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - AMBITIONS.{ext}.mp3" },
        { title: "CARTIER", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - CARTIER.{ext}.mp3" },
        { title: "FLEURS", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - FLEURS (feat. Tiakola).{ext}.mp3" },
        { title: "INTERLUDE", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - INTERLUDE.{ext}.mp3" },
        { title: "KASSAV", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - KASSAV (feat. Tiakola).{ext}.mp3" },
        { title: "MAMI WATA", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - MAMI WATA.{ext}.mp3" },
        { title: "NOTRE DAME (feat. Angèle)", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - NOTRE DAME (feat. Angèle).{ext}.mp3" },
        { title: "NOTRE DAME", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - NOTRE DAME.{ext}.mp3" },
        { title: "OUTRO", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - OUTRO.{ext}.mp3" },
        { title: "SOBAD", album: "La Mélo est Gangx", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gazo - SOBAD.{ext}.mp3" }
    ],
    "Single": [
        { title: "Pousse toi", album: "Single", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Pousse toi.{ext}.mp3" },
        { title: "Sombre mélodie", album: "Single", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - Sombre mélodie.{ext}.mp3" },
        { title: "T.I.A - A COLORS SHOW", album: "Single", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tiakola - T.I.A - A COLORS SHOW.{ext}.mp3" }
    ],
    "Feat.": [
        { title: "Ami ou ennemi (Alonzo)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Alonzo - Ami ou ennemi.{ext}.mp3" },
        { title: "BADMAN GANGSTA (Asake)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Asake - BADMAN GANGSTA.{ext}.mp3" },
        { title: "Cadeau (Aya Nakamura)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Aya Nakamura - Cadeau (feat. Tiakola).{ext}.mp3" },
        { title: "Près du cœur (BU$HI)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/BU$HI - Près du cœur.{ext}.mp3" },
        { title: "APPEL MANQUÉ (Booska-P)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Booska-P - APPEL MANQUÉ.{ext}.mp3" },
        { title: "Où sont mes amis (Chily)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Chily - Où sont mes amis  (feat. Tiakola).{ext}.mp3" },
        { title: "Capi (Cinco)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Cinco - Capi.{ext}.mp3" },
        { title: "Dieu merci (Dadju)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Dadju - Dieu merci.{ext}.mp3" },
        { title: "Meridian (Dave)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Dave - Meridian.{ext}.mp3" },
        { title: "Special (Dave)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Dave - Special.{ext}.mp3" },
        { title: "GAÙCHO (Dinos)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Dinos - GAÙCHO.{ext}.mp3" },
        { title: "Prends mes lovés (Dinos)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Dinos - Prends mes lovés.{ext}.mp3" },
        { title: "Plus belle la vie... (Dosseh)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Dosseh - Plus belle la vie, plus belle la mort.{ext}.mp3" },
        { title: "Biberon (Franglish)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Franglish - Biberon.{ext}.mp3" },
        { title: "Reste-là (Gambino La MG)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Gambino La MG - Reste-là (feat. Tiakola).{ext}.mp3" },
        { title: "LA MELO EST DANS LA BOUNCE", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Genezio - LA MELO EST DANS LA BOUNCE.{ext}.mp3" },
        { title: "bank (Green Montana)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Green Montana - bank.{ext}.mp3" },
        { title: "Atasanté Part.2 (Hamza)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Hamza - Atasanté Part.2.{ext}.mp3" },
        { title: "BALLE DANS LE COEUR (Ikaz Boi)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Ikaz Boi - BALLE DANS LE COEUR.{ext}.mp3" },
        { title: "Cadenacer (JEY BROWNIE)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/JEY BROWNIE - Cadenacer.{ext}.mp3" },
        { title: "Délire (Joé Dwèt Filé)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Joé Dwèt Filé - Délire (feat. Tiakola).{ext}.mp3" },
        { title: "Miné sur Paname (Jul)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Jul - Miné sur Paname.{ext}.mp3" },
        { title: "500 (La Fève)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/La Fève - 500.{ext}.mp3" },
        { title: "Crime ensoleillé (La Mano 1.9)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/La Mano 1.9 - Crime ensoleillé.{ext}.mp3" },
        { title: "God Bless (Leto)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Leto - God Bless.{ext}.mp3" },
        { title: "Kiffe la mode (Leto)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Leto - Kiffe la mode (feat. Naza & Tiakola).{ext}.mp3" },
        { title: "Mood (Liim’s)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Liim’s - Mood.{ext}.mp3" },
        { title: "4 Decembre (Lyele)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Lyele - 4 Decembre.{ext}.mp3" },
        { title: "Pololo (MHD)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/MHD - Pololo.{ext}.mp3" },
        { title: "CARGO (Mac Tyer)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Mac Tyer - CARGO (feat. Tiakola).{ext}.mp3" },
        { title: "Mardi gras (Maes)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Maes - Mardi gras.{ext}.mp3" },
        { title: "Quand j'y repense (Mig)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Mig - Quand j'y repense.{ext}.mp3" },
        { title: "Une histoire (Naza)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Naza - Une histoire.{ext}.mp3" },
        { title: "Joe Pesci (Niska)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Niska - Joe Pesci.{ext}.mp3" },
        { title: "Journée (Niska)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Niska - Journée.{ext}.mp3" },
        { title: "COMPACT (Prinzly)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Prinzly - COMPACT.{ext}.mp3" },
        { title: "Bob Marley (Prototype)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Prototype - Bob Marley (feat. Tiakola).{ext}.mp3" },
        { title: "Cocaina (Prototype)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Prototype - Cocaina (feat. Tiakola & Liim's).{ext}.mp3" },
        { title: "Snake #3 (Prototype)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Prototype - Snake #3 (Pause) [feat. Tiakola].{ext}.mp3" },
        { title: "PSYCHOLOGIQUE (Remix)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/RUSH AVENUE - PSYCHOLOGIQUE (Remix).{ext}.mp3" },
        { title: "Comme moi (Ronisia)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Ronisia - Comme moi (feat. Tiakola).{ext}.mp3" },
        { title: "Bosseur (Rsko)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Rsko - Bosseur (feat. Tiakola).{ext}.mp3" },
        { title: "Palavé (Rsko)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Rsko - Palavé (feat. Tiakola).{ext}.mp3" },
        { title: "Bonsoir Paris (S.Pri Noir)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/S.Pri Noir - Bonsoir Paris (Mama No Cry).{ext}.mp3" },
        { title: "J'Y PENSE (SDM)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/SDM - J'Y PENSE.{ext}.mp3" },
        { title: "Redescends (SDM)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/SDM - Redescends (feat Tiakola).{ext}.mp3" },
        { title: "STABILITÉ (Tarik Azzouz)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tarik Azzouz - STABILITÉ.{ext}.mp3" },
        { title: "P A S C O M M E Ç A (Tayc)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Tayc - P A S C O M M E Ç A.{ext}.mp3" },
        { title: "M3 (Theodorepourdevrai)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Theodorepourdevrai - M3 (feat. Tiakola).{ext}.mp3" },
        { title: "Tout seul (Werenoi)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Werenoi - Tout seul.{ext}.mp3" },
        { title: "Après Minuit (Wizkid)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Wizkid - Après Minuit (feat. Tiakola).{ext}.mp3" },
        { title: "Me sauver (Zed)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Zed - Me sauver.{ext}.mp3" },
        { title: "TOUTE LA JOURNÉE (Zola)", album: "Feat.", url: "https://storage.googleapis.com/blind-test-red-empire/tiakola/Zola - TOUTE LA JOURNÉE (feat. Tiakola).{ext}.mp3" }
    ]
};

export const ALBUM_COVERS = {
    "BDLM Vol. 1": "https://images.genius.com/0c4415494d4d6824f2b9678122c6722d.1000x1000x1.jpg",
    "Mélo": "https://images.genius.com/b2a7575215d2639074092440333333b2.1000x1000x1.jpg",
    "La Mélo est Gangx": "https://images.genius.com/9b005892557451475751939801865809.1000x1000x1.jpg",
    "Single": "https://cdns-images.dzcdn.net/images/cover/d40d96570560a6639525287515104618/500x500.jpg",
    "Feat.": "https://cdns-images.dzcdn.net/images/artist/b282713f06c4b266d62325089228498d/500x500.jpg"
};
